// jest-dom adds custom jest matchers for asserting on DOM nodes.
// allows you to do things like:
// expect(element).toHaveTextContent(/react/i)
import '@testing-library/jest-dom';

// Mock canvas for WebGL (ogl library)
HTMLCanvasElement.prototype.getContext = jest.fn(() => ({
  viewport: jest.fn(),
  clearColor: jest.fn(),
  enable: jest.fn(),
  disable: jest.fn(),
  blendFunc: jest.fn(),
  blendEquation: jest.fn(),
  depthMask: jest.fn(),
  depthFunc: jest.fn(),
  cullFace: jest.fn(),
  frontFace: jest.fn(),
  clear: jest.fn(),
  createShader: jest.fn(() => ({})),
  shaderSource: jest.fn(),
  compileShader: jest.fn(),
  getShaderParameter: jest.fn(() => true),
  createProgram: jest.fn(() => ({})),
  attachShader: jest.fn(),
  linkProgram: jest.fn(),
  getProgramParameter: jest.fn(() => true),
  useProgram: jest.fn(),
  getUniformLocation: jest.fn(),
  getAttribLocation: jest.fn(),
  createBuffer: jest.fn(() => ({})),
  bindBuffer: jest.fn(),
  bufferData: jest.fn(),
  enableVertexAttribArray: jest.fn(),
  vertexAttribPointer: jest.fn(),
  createTexture: jest.fn(() => ({})),
  bindTexture: jest.fn(),
  texImage2D: jest.fn(),
  texParameteri: jest.fn(),
  generateMipmap: jest.fn(),
  uniform1f: jest.fn(),
  uniform1i: jest.fn(),
  uniform2f: jest.fn(),
  uniform2fv: jest.fn(),
  uniform3f: jest.fn(),
  uniform3fv: jest.fn(),
  uniform4f: jest.fn(),
  uniform4fv: jest.fn(),
  uniformMatrix3fv: jest.fn(),
  uniformMatrix4fv: jest.fn(),
  drawArrays: jest.fn(),
  drawElements: jest.fn(),
  getExtension: jest.fn(() => null),
  getParameter: jest.fn(() => 16),
  pixelStorei: jest.fn(),
  activeTexture: jest.fn(),
  createFramebuffer: jest.fn(() => ({})),
  bindFramebuffer: jest.fn(),
  framebufferTexture2D: jest.fn(),
  createRenderbuffer: jest.fn(() => ({})),
  bindRenderbuffer: jest.fn(),
  renderbufferStorage: jest.fn(),
  framebufferRenderbuffer: jest.fn(),
  checkFramebufferStatus: jest.fn(() => 36053),
  deleteFramebuffer: jest.fn(),
  deleteRenderbuffer: jest.fn(),
  deleteTexture: jest.fn(),
  deleteBuffer: jest.fn(),
  deleteProgram: jest.fn(),
  deleteShader: jest.fn(),
  scissor: jest.fn(),
  colorMask: jest.fn(),
  stencilMask: jest.fn(),
  stencilFunc: jest.fn(),
  stencilOp: jest.fn(),
  canvas: {
    width: 800,
    height: 600,
  },
  drawingBufferWidth: 800,
  drawingBufferHeight: 600,
}));

// Mock window.requestAnimationFrame
window.requestAnimationFrame = jest.fn((cb) => setTimeout(cb, 16));
window.cancelAnimationFrame = jest.fn((id) => clearTimeout(id));

// Mock ResizeObserver
window.ResizeObserver = jest.fn().mockImplementation(() => ({
  observe: jest.fn(),
  unobserve: jest.fn(),
  disconnect: jest.fn(),
}));